name: budoux
description: a Dart port of BudouX, the machine learning powered line break organizer tool.
repository: https://github.com/i10416/budoux/core
version: 0.0.1
environment:
  sdk: '>2.12.0 <3.0.0'
dependencies:
  mustache_template: ^2.0.0
  characters: ^1.2.0
  tuple: ^2.0.0
dev_dependencies:
  test: ^1.20.1
